name: Telegram Notification

on: [push]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Notification
        env:
          TELEGRAM_CHAT_ID: "-1001964570396" # <-- Replace with your chat ID (HARD CODED)
          TELEGRAM_BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          COMMIT_MSG: ${{ github.event.commits[0].message }}
          REPO: ${{ github.repository }}
          BRANCH: ${{ github.ref }}
          COMMIT_URL: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
          AUTHOR_URL: https://github.com/${{ github.actor }}
          USER: ${{ github.actor }}
        run: |
          BD_TIMESTAMP=$(TZ="Asia/Dhaka" date -d "${{ github.event.head_commit.timestamp }}" "+%Y-%m-%d %H:%M:%S")

          MESSAGE="New Commit Pushed\n"
          MESSAGE+="\n"
          MESSAGE+="Commit by: [${USER}](${AUTHOR_URL})\n"
          MESSAGE+="Repository: ${REPO}\n"
          MESSAGE+="Branch: ${BRANCH}\n"
          MESSAGE+="Pushed at: ${BD_TIMESTAMP}\n"
          MESSAGE+="\n"
          MESSAGE+="Commit Message:\n"
          MESSAGE+="${COMMIT_MSG}\n"
          MESSAGE+="\n"
          MESSAGE+="[View Commit Details](${COMMIT_URL})"

          curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
          -H "Content-Type: application/json" \
          -d '{
            "chat_id": "'"${TELEGRAM_CHAT_ID}"'",
            "text": "'"${MESSAGE}"'",
            "parse_mode": "Markdown",
            "disable_web_page_preview": true
          }'